//Types for Login
export const GET_SMS_CODE_REQUEST = 'GET_SMS_CODE_REQUEST';
export const GET_SMS_CODE_SUCCESS = 'GET_SMS_CODE_SUCCESS';
export const GET_SMS_CODE_FAILURE = 'GET_SMS_CODE_FAILURE';

//Types for Logout
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

//Types for Delete account
export const DELETE_ACCOUNT_REQUEST = 'DELETE_ACCOUNT_REQUEST';
export const DELETE_ACCOUNT_SUCCESS = 'DELETE_ACCOUNT_SUCCESS';
export const DELETE_ACCOUNT_FAILURE = 'DELETE_ACCOUNT_FAILURE';

//Types for Logout
export const VERIFY_CODE_REQUEST = 'VERIFY_CODE_REQUEST';
export const VERIFY_SIGNUP_CODE_SUCCESS = 'VERIFY_SIGNUP_CODE_SUCCESS';
export const VERIFY_LOGIN_CODE_SUCCESS = 'VERIFY_LOGIN_CODE_SUCCESS';
export const VERIFY_CODE_FAILURE = 'VERIFY_CODE_FAILURE';

//Types for Setting
export const GET_SETTINGS_REQUEST = 'GET_SETTINGS_REQUEST';
export const GET_SETTINGS_SUCCESS = 'GET_SETTINGS_SUCCESS';
export const PUT_SETTINGS_SUCCESS = 'PUT_SETTINGS_SUCCESS';
export const GET_SETTINGS_FAILURE = 'GET_SETTINGS_FAILURE';
