//Types for Login
export const GET_SMS_CODE_REQUEST = 'GET_SMS_CODE_REQUEST';
export const GET_SMS_CODE_SUCCESS = 'GET_SMS_CODE_SUCCESS';
export const GET_SMS_CODE_FAILURE = 'GET_SMS_CODE_FAILURE';

//Types for Logout
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

//Types for Signup
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

//Types for Delete account
export const DELETE_ACCOUNT_REQUEST = 'DELETE_ACCOUNT_REQUEST';
export const DELETE_ACCOUNT_SUCCESS = 'DELETE_ACCOUNT_SUCCESS';
export const DELETE_ACCOUNT_FAILURE = 'DELETE_ACCOUNT_FAILURE';

//Types for Logout
export const VERIFY_CODE_REQUEST = 'VERIFY_CODE_REQUEST';
export const VERIFY_SIGNUP_CODE_SUCCESS = 'VERIFY_SIGNUP_CODE_SUCCESS';
export const VERIFY_LOGIN_CODE_SUCCESS = 'VERIFY_LOGIN_CODE_SUCCESS';
export const VERIFY_CODE_FAILURE = 'VERIFY_CODE_FAILURE';

//Types for Setting
export const GET_SETTINGS_REQUEST = 'GET_SETTINGS_REQUEST';
export const GET_SETTINGS_SUCCESS = 'GET_SETTINGS_SUCCESS';
export const PUT_SETTINGS_SUCCESS = 'PUT_SETTINGS_SUCCESS';
export const GET_SETTINGS_FAILURE = 'GET_SETTINGS_FAILURE';

export const GET_LABELS_REQUEST = 'GET_LABELS_REQUEST';
export const GET_LABELS_SUCCESS = 'GET_LABELS_SUCCESS';
export const GET_LABELS_FAILURE = 'GET_LABELS_FAILURE';

export const SEND_INVITATION_REQUEST = 'SEND_INVITATION_REQUEST';
export const SEND_INVITATION_SUCCESS = 'SEND_INVITATION_SUCCESS';
export const SEND_INVITATION_FAILURE = 'SEND_INVITATION_FAILURE';

export const EDIT_INVITATION_REQUEST = 'EDIT_INVITATION_REQUEST';
export const EDIT_INVITATION_SUCCESS = 'EDIT_INVITATION_SUCCESS';
export const EDIT_INVITATION_FAILURE = 'EDIT_INVITATION_FAILURE';

export const ACCEPT_INVITATION_REQUEST = 'ACCEPT_INVITATION_REQUEST';
export const ACCEPT_INVITATION_SUCCESS = 'ACCEPT_INVITATION_SUCCESS';
export const ACCEPT_INVITATION_FAILURE = 'ACCEPT_INVITATION_FAILURE';

export const GET_INVI_DETAIL_REQUEST = 'GET_INVI_DETAIL_REQUEST';
export const GET_INVI_DETAIL_SUCCESS = 'GET_INVI_DETAIL_SUCCESS';
export const GET_INVI_DETAIL_FAILURE = 'GET_INVI_DETAIL_FAILURE';

export const FEEDBACK_REQUEST = 'FEEDBACK_REQUEST';
export const FEEDBACK_SUCCESS = 'FEEDBACK_SUCCESS';
export const FEEDBACK_FAILURE = 'FEEDBACK_FAILURE';

export const USER_SEARCH_REQUEST = 'USER_SEARCH_REQUEST';
export const USER_SEARCH_SUCCESS = 'USER_SEARCH_SUCCESS';
export const USER_SEARCH_FAILURE = 'USER_SEARCH_FAILURE';

export const REGISTER_NOTIFY_REQUEST = 'REGISTER_NOTIFY_REQUEST';
export const REGISTER_NOTIFY_SUCCESS = 'REGISTER_NOTIFY_SUCCESS';
export const REGISTER_NOTIFY_FAILURE = 'REGISTER_NOTIFY_FAILURE';
