//Types for Login
export const GET_SMS_CODE_REQUEST = 'GET_SMS_CODE_REQUEST';
export const GET_SMS_CODE_SUCCESS = 'GET_SMS_CODE_SUCCESS';
export const GET_SMS_CODE_FAILURE = 'GET_SMS_CODE_FAILURE';

//Types for Logout
export const VERIFY_CODE_REQUEST = 'VERIFY_CODE_REQUEST';
export const VERIFY_CODE_SUCCESS = 'VERIFY_CODE_SUCCESS';
export const VERIFY_CODE_FAILURE = 'VERIFY_CODE_FAILURE';
