# Generated by Django 2.2.2 on 2020-11-07 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201106_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='available_to',
            field=models.CharField(choices=[('professional_snack', 'Professional Snack'), ('friendly_snack', 'Friendly Snack'), ('active_snack', 'Active Snack'), ('romantic_snack', 'Romantic Snack')], default=None, max_length=6),
        ),
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='career_field',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default=None, max_length=6),
        ),
        migrations.AddField(
            model_name='user',
            name='gender_preference',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('both', 'Both')], default=None, max_length=6),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='preference_time',
            field=models.CharField(choices=[('brunch', 'Brunch (9 AM - 12 PM)'), ('lunch', 'Lunch (12 PM - 3 PM)'), ('happy_hour', 'Happy hour (3 PM - 6 PM)'), ('dinner', 'Dinner (6 PM - 10 PM)'), ('late_night', 'Late night (10PM +)')], default=None, max_length=6),
        ),
        migrations.CreateModel(
            name='ProfileImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='profile_images')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
