# Generated by Django 2.2.2 on 2020-12-01 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import snak_snak_16642.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20201107_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileimages',
            name='image',
            field=models.ImageField(storage=snak_snak_16642.storage_backends.PrivateMediaStorage(), upload_to=''),
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_snak_invites', models.BooleanField(default=True)),
                ('notify_meeting_reminder', models.BooleanField(default=True)),
                ('notify_canceled_meeting', models.BooleanField(default=True)),
                ('notify_deleted_meeting', models.BooleanField(default=True)),
                ('notify_meeting_update', models.BooleanField(default=True)),
                ('hide_your_profile', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
