# Generated by Django 2.2.2 on 2020-12-15 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20201201_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='available_to',
        ),
        migrations.RemoveField(
            model_name='user',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='user',
            name='career_field',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='preference_time',
        ),
        migrations.AddField(
            model_name='user',
            name='age_preferred',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='distance_preferred',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='expertise_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='job_field',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ocuppation',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_expertise_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default=None, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='UserSports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sports', models.CharField(choices=[('baseball', 'Baseball'), ('basketball', 'Basketball'), ('cycling', 'Cycling'), ('dodgeball', 'Dodgeball'), ('fishing', 'Fishing'), ('football', 'Football'), ('golf', 'Golf'), ('hiking', 'Hiking'), ('mountain_biking', 'Mountain Biking'), ('racquetball', 'Racquetball'), ('skiing_snowboarding', 'Skiing / Snowboarding'), ('soccer', 'Soccer'), ('tennis', 'Tennis'), ('volleyball', 'Volleyball')], default=None, max_length=6)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
