# Generated by Django 2.2.2 on 2020-12-16 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20201215_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender_preference',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('both', 'Both')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='usersports',
            name='sports',
            field=models.CharField(choices=[('baseball', 'Baseball'), ('basketball', 'Basketball'), ('cycling', 'Cycling'), ('dodgeball', 'Dodgeball'), ('fishing', 'Fishing'), ('football', 'Football'), ('golf', 'Golf'), ('hiking', 'Hiking'), ('mountain_biking', 'Mountain Biking'), ('racquetball', 'Racquetball'), ('skiing_snowboarding', 'Skiing / Snowboarding'), ('soccer', 'Soccer'), ('tennis', 'Tennis'), ('volleyball', 'Volleyball')], default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='usersports',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sports', to=settings.AUTH_USER_MODEL),
        ),
    ]
