# Generated by Django 2.2.2 on 2021-01-13 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210113_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='job_field',
        ),
        migrations.CreateModel(
            name='JobFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_field', models.CharField(choices=[('agriculture', 'Agriculture'), ('business_and_administration', 'Business and Administration'), ('communications', 'Communications'), ('community_entertainment', 'Community & Entertainment'), ('education', 'Education'), ('emergency_services', 'Emergency Services'), ('government', 'Government'), ('health_wellness', 'Health & Wellness'), ('hospitality_travel', 'Hospitality & Travel'), ('law', 'Law'), ('medical', 'Medical'), ('sales', 'Sales'), ('science_technology', 'Science & Technology'), ('sports', 'Sports')], default=None, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_job_fields', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
