# Generated by Django 2.2.2 on 2021-01-14 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210113_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notify_id',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
