# Generated by Django 2.2.2 on 2021-01-14 22:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_invitations'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitations',
            name='room_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
