# Generated by Django 2.2.2 on 2021-01-14 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_invitations_room_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitations',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='invitations',
            name='message',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='invitations',
            name='place',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='invitations',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
