# Generated by Django 2.2.2 on 2021-01-14 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20210114_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitations',
            name='feedback',
            field=models.BooleanField(default=False),
        ),
    ]
