# Generated by Django 2.2.2 on 2021-01-19 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_invitations_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobfields',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_jobs', to=settings.AUTH_USER_MODEL),
        ),
    ]
