# Generated by Django 2.2.2 on 2021-01-22 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20210119_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobfields',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profileimages',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile_image', to=settings.AUTH_USER_MODEL),
        ),
    ]
