# Generated by Django 2.2.2 on 2021-01-16 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_subscription_usersubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='monthly_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='yearly_price',
            field=models.FloatField(null=True),
        ),
    ]
