# Generated by Django 2.2.2 on 2021-01-16 22:18

from django.db import migrations, transaction

from users.models import Subscription


@transaction.atomic
def subscription_plans(apps, schema_editor):

    subscription = [
        {
            'plan': 'Snak Snak Prime',
            'price_monthly': 5.99,
            'price_yearly': 50
        },
        {
            'plan': 'Snak Snak Elite',
            'price_monthly': 10.99,
            'price_yearly': 100
        },
        {
            'plan': 'Snak Snak Artist',
            'price_monthly': None,
            'price_yearly': None
        }
    ]

    for sub in subscription:
        address = Subscription(
            plan=sub["plan"],
            monthly_price=sub["price_monthly"],
            yearly_price=sub["price_yearly"]
        )
        address.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20210116_2218'),
    ]

    operations = [
        migrations.RunPython(subscription_plans),
    ]
