# Generated by Django 2.2.17 on 2021-03-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20210122_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender_preference',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('both', 'Both')], default=None, max_length=20, null=True),
        ),
    ]
