# Generated by Django 2.2.17 on 2021-03-26 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20210320_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileimages',
            name='image',
            field=models.ImageField(upload_to='user_profile_pictures'),
        ),
    ]
