# Generated by Django 2.2.28 on 2022-06-20 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20220620_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ocuppation',
        ),
        migrations.AddField(
            model_name='user',
            name='occupation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
