# Generated by Django 2.2.28 on 2022-06-21 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublicPrivateKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(max_length=24)),
                ('public_key', models.CharField(max_length=40)),
                ('private_key', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'PublicPrivateKeys',
            },
        ),
        migrations.CreateModel(
            name='TwilioSms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_phone', models.CharField(max_length=18)),
                ('to_phone', models.CharField(max_length=18)),
                ('message', models.CharField(max_length=160)),
                ('send_status', models.CharField(default='created, not sent', max_length=24)),
                ('success', models.BooleanField(default=False)),
                ('error_status', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'TwilioSmss',
            },
        ),
    ]
