# Generated by Django 2.2.28 on 2022-06-22 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userverifytoken_userverifytry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userverifytoken',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
